# Generated by Django 4.2 on 2023-04-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platoon',
            name='platoon',
            field=models.JSONField(null=True),
        ),
    ]
