# Generated by Django 4.2 on 2023-04-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_rename_platoon_platoon_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='platoon',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platoon',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platoon',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
