# Generated by Django 4.2 on 2023-04-26 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_platoon_branch_platoon_country_platoon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='platoon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
