# Generated by Django 4.2 on 2023-04-27 17:57

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_platoon_notes_platoon_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='platoon',
            name='era',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(null=True),
        ),
    ]
